# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base:3.18
  amd64: ghcr.io/home-assistant/amd64-base:3.18
  armhf: ghcr.io/home-assistant/armhf-base:3.18
  armv7: ghcr.io/home-assistant/armv7-base:3.18
  i386: ghcr.io/home-assistant/i386-base:3.18
labels:
  org.opencontainers.image.title: "Custom Nginx"
  org.opencontainers.image.description: "Customizable Nginx Add-On (derived from https://github.com/home-assistant/addons/tree/master/nginx_proxy)"
  org.opencontainers.image.source: "https://github.com/tienducle/home-assistant-addons/custom-nginx"
  org.opencontainers.image.licenses: "Apache License 2.0"