---
name: Custom Nginx
version: 0.0.1
slug: custom_nginx
description: "Customizable Nginx Add-On (derived from https://github.com/home-assistant/addons/tree/master/nginx_proxy)"
url: 'https://github.com/tienducle/ha-addon-custom-nginx'
image: 'ghcr.io/tienducle/ha-addon-custom-nginx-{arch}'
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
hassio_api: true
init: false
stage: experimental
map:
  - ssl
  - config
options:
  domain: null
  use_default_http_config: false
  use_default_https_config: false
  certificate_file: fullchain.pem
  private_key_file: privkey.pem
  advanced: false
  custom_config_path: /config/custom_nginx
ports:
  443/tcp: 443
  80/tcp: null
schema:
  domain: str
  use_default_http_config: bool
  use_default_https_config: bool
  certificate_file: str
  private_key_file: str
  advanced: bool
  custom_config_path: str
